[book]
authors = ["Hasan Kurşun"]
language = "en"
multilingual = false
src = "src"
title = "lumindd v1.0.0"
description = "Complete guide to the lumindd decision diagram library"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Lumees/lumindd"
additional-css = ["theme/custom.css"]
mathjax-support = false
no-section-label = false
